channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=21.2.3
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
